Yaml and legacy output tests
openmicroscopy/openmicroscopy pull request #4880
Opened 2016-10-05 15:56 UTC by pwalczysko

# What this PR does
A follow-up pf https://github.com/openmicroscopy/openmicroscopy/pull/4873 where the tests for import output in case --legacy flag and --yaml flag are being passed.

As the output form of import commands changed in https://github.com/openmicroscopy/openmicroscopy/pull/4812, this PR is adjusting the import integration tests in such a manner that the new flag options --legacy and --yaml are being tested.

# Testing this PR

Check the integration tests are passing.
Check the sensibility of the test additions here.

yaml library is necessary for these tests to pass, thank you @joshmoore 

@mtbc @jburel

2016-10-06 08:48 UTC, manics commented on components/tools/OmeroPy/test/integration/clitest/test_import.py
> +        elif import_type == 'legacy':
You can never get here because it's matched by the earlier `if import_type == 'default' or import_type == 'legacy':`

2016-10-06 11:28 UTC, pwalczysko commented
This should fix the comment, thank you @manics

2016-10-07 10:27 UTC, pwalczysko commented
It seems to me that both breaking python integration jobs are now passing with this PR.
Time to remove --breaking label, @joshmoore @manics ?

2016-10-07 13:24 UTC, joshmoore commented
It's not this PRs fault, but I think the tests are not being run:

```
09:49:00 E   ValueError: ids must be list of strings, found: <test.integration.clitest.test_download.PolicyFixture object at 0x5ca0b50> (type: PolicyFixture)
09:49:00 !!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
09:49:00 ============================= 33 tests deselected ==============================
```

from https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-breaking-integration-Python27/53/consoleFull

i.e. the capping of pytest is no longer in place. cc: @jburel @aleksandra-tarkowska

2016-10-14 08:57 UTC, pwalczysko commented
This is waiting for https://github.com/openmicroscopy/openmicroscopy/pull/4886

2016-10-14 09:25 UTC, pwalczysko commented
@aleksandra-tarkowska advised that the capping of python is not the problem here. Rather, changes in the merge/breaking part of the CI are the culprit. @aleksandra-tarkowska is on the case - thank you .

2016-10-14 09:27 UTC, mtbc commented
@pwalczysko: See https://trello.com/c/1AQPp5vJ/2351-fyi-breaking-includes-merge.

2016-10-14 09:29 UTC, aleksandra-tarkowska commented
both PRs, https://github.com/openmicroscopy/openmicroscopy/pull/4886 and this PR are in https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-push/825/console

2016-10-14 09:31 UTC, joshmoore commented
But https://github.com/openmicroscopy/openmicroscopy/pull/4886 does not yet include https://github.com/openmicroscopy/openmicroscopy/pull/4853/commits/cfbfac97896dc67f5e3f63e6bece62acaf78e09c

2016-10-14 13:46 UTC, pwalczysko commented
https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-integration-python/659/ passed in general (with this PR in) - I do not seem to be able to see test-by-test passing test results on integration-python builds.
python27 I see as passing too
https://ci.openmicroscopy.org/view/Breaking/job/OMERO-DEV-breaking-integration-Python27/61/testReport/OmeroPy.test.integration.clitest.test_import/TestImport/testImportOutputLegacy/
and 
https://ci.openmicroscopy.org/view/Breaking/job/OMERO-DEV-breaking-integration-Python27/61/testReport/OmeroPy.test.integration.clitest.test_import/TestImport/testImportOutputYaml/

So can I remove the --breaking @joshmoore @manics ?

2016-10-15 07:45 UTC, aleksandra-tarkowska commented
Bringing new dependences requires adjustments in few other repositories. I think we already discussed the whole workflow, see https://github.com/openmicroscopy/ome-documentation/pull/1495. OMERO.web deployment has been recently improved to simplify the process, but OMERO.py (and server package) not yet. Installing yaml package manually is not a solution.

Devspace failure https://10.0.51.106:8443/job/OMERO-test-integration/1/testReport/:

```
Stacktrace

test/integration/clitest/test_import.py:28: in <module>
    import yaml
E   ImportError: No module named yaml
```

I think this PR could be a driver on how we would like to handle PyPi Py/Server packages.

My proposal is to add `requirements-py2*.txt` for OMERO.py (the same as https://github.com/openmicroscopy/openmicroscopy/blob/develop/build.xml#L735). Then consume it with virtualenv the same way as web (see integration jobs for more examples).

2016-10-15 07:46 UTC, atarkowska requested changes
Bringing new dependences separate testing first, and/or adjustments in few other repositories. I think we already discussed the whole workflow https://trello.com/c/Nare6gZN/151-devspace-vs-main-line-prerequisites, see https://github.com/openmicroscopy/ome-documentation/pull/1495. OMERO.web deployment has been recently improved to simplify the process, but OMERO.py (and server package) not yet. Installing yaml package manually is not a solution.

Devspace failure https://10.0.51.106:8443/job/OMERO-test-integration/1/testReport/:

```
Stacktrace

test/integration/clitest/test_import.py:28: in <module>
    import yaml
E   ImportError: No module named yaml
```

---

> [12:20]  @joshmoore: the VIRTUALENV-upgrade job should be installing PyYAML, but if you want to move (further) away from the job in favor of requirements files, +1

As PyYAML is already installed in VIRTUALENV-upgrade:
**Option 1**: I think this PR could be a driver on how we would like to handle PyPi Py/Server packages. My proposal is to add `requirements.txt`, see https://www.python.org/dev/peps/pep-0345/#environment-markers, to OMERO.py (the same as https://github.com/openmicroscopy/openmicroscopy/blob/develop/build.xml#L735). Then consume it with virtualenv the same way as web (see https://github.com/openmicroscopy/management_tools/pull/223).

Although be careful with the version:
**Option 2**: Latest `PyYAML` requires Python 2.7 or Python 3.4+, http://pyyaml.org/wiki/PyYAML. Is that really good idea to upgrade VIRTUALENV-upgrade on c6 nodes? Does it mean we are going to drop Python 2.6 from server as well? Looks like ubuntu and c7 install 3.10. Is that still considered as PyPi requirement or it should be installed from RPMs.

2016-10-15 07:46 UTC, aleksandra-tarkowska commented on components/tools/OmeroPy/test/integration/clitest/test_import.py
> +import yaml
```
Stacktrace

test/integration/clitest/test_import.py:28: in <module>
    import yaml
E   ImportError: No module named yaml
```

2016-10-15 07:49 UTC, aleksandra-tarkowska commented
I would `--exclude` this PR until this problem is resolved

2016-10-16 20:17 UTC, aleksandra-tarkowska commented
Did we know that `PyYAML` requires Python 2.7 or Python 3.4+. Does it mean we are going to drop py26 from server as well?

2017-01-18 21:49 UTC, aleksandra-tarkowska commented
@pwalczysko it took quite a while :) New dependences were added to omero-install so with https://github.com/openmicroscopy/devspace/pull/63 you would be able to test this in devspace. I will ping you once new devspace for 5.3 is available

2017-01-19 11:17 UTC, pwalczysko commented
Great, thanks

2017-02-27 16:09 UTC, jburel commented
What's the status of this PR @pwalczysko?

2017-02-27 16:17 UTC, pwalczysko commented
Waiting for ping of @aleksandra-tarkowska about the new 5.3 devspace. Maybe I missed something ? The feature and test are otherwise ready, it is just the missing yaml library on the CI which blocks it here.

2017-02-27 16:52 UTC, aleksandra-tarkowska commented
you should be fine now, removing --exclude

2017-02-27 16:53 UTC, pwalczysko commented
@aleksandra-tarkowska : Thank you, removed. Will have a look tomorrow.

2017-03-01 11:55 UTC, pwalczysko commented
The tests are passing on breaking, see e.g. https://ci.openmicroscopy.org/view/Breaking/job/OMERO-DEV-breaking-integration-python/lastCompletedBuild/testReport/OmeroPy.test.integration.clitest.test_import/TestImport/testImportOutputYaml/.
The PR was in the merge as checked on https://github.com/snoopycrimecop/openmicroscopy/commit/cac35cf7c690ad3839e57d5a6f1c0779c600f623.

Can I remove the --breaking flag @jburel  ?

2017-03-01 13:14 UTC, jburel commented
@pwalczysko please do

2017-03-01 22:06 UTC, jburel commented
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-Python27/lastCompletedBuild/testReport/(root)/(empty)/OmeroPy_test_integration_clitest_test_import/

2017-03-02 12:06 UTC, jburel commented
PyYaml has now been installed on cowfish.

2017-03-02 12:52 UTC, jburel commented
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-Python27/469/ 
the previous test failures is now gone

2017-03-02 13:15 UTC, jburel commented
11:49:44 test/integration/clitest/test_import.py::TestImport::testImportOutputDefault PASSED
11:49:48 test/integration/clitest/test_import.py::TestImport::testImportOutputYaml PASSED

2017-03-02 13:16 UTC, merged

2017-03-02 13:19 UTC, pwalczysko commented
@jburel Thank you.