Arrow shapes (Insight)
openmicroscopy/openmicroscopy pull request #4887
Opened 2016-10-11 17:49 UTC by dominikl

# What this PR does

Corresponding Insight PR to #4690 .
Adds the possibility to specify Arrows as start and/or end of a Line ROI.

Not ready for review yet. At the moment Insight displays the arrows and you can set an arrow by setting the Start/End decoration property via the Inspector to "Arrow", but there's no graphical support in the line drawing tool yet.

# Testing this PR

# Related reading

2016-10-18 06:48 UTC, dominikl commented
Is the functionality sufficient for now, or do we need an explicit "arrow" drawing tool (like line, point, etc) in the toolbar?

2016-10-18 09:55 UTC, will-moore commented
Looks good. There's a bit of difference in terms of Arrow head size between web and Insight. Don't know which we prefer (or how hard it is to change in Insight)? Pretty easy to change in web if we want to align them?

<img width="1146" alt="screen shot 2016-10-18 at 10 42 01" src="https://cloud.githubusercontent.com/assets/900055/19472786/97b946d4-9520-11e6-9a52-12b9b0cc39fd.png">

I think an "Arrow" tool might be nice, just to make it a bit easier and to help users discover this feature.
I guess it depends on how hard that would be. Looks like we have enough space in the toolbar for an Arrow icon (ImageJ puts it under a right-click on the line icon).
I think you should still be able to create an Arrow from a line (and vice versa) just as you can now (rather than have a fixed Arrow shape).

2016-10-18 10:35 UTC, dominikl commented
Changing the arrow size would be pretty easy in Insight, too. Should that be hard coded or configurable? And yes, I'll try to add an "arrow" drawing tool to the toolbar.

2016-10-18 12:36 UTC, dominikl commented
Just tried to change the size of the arrows in Insight, then they slightly change their shape, too. So might be easier to adjust that in OMERO.web.

2016-10-18 18:28 UTC, jburel requested changes

2016-10-18 18:28 UTC, jburel commented on components/blitz/src/omero/gateway/model/ShapeSettingsData.java
> +        Shape shape = (Shape) asIObject();
I will add a `null` check for `start`

2016-10-18 18:28 UTC, jburel commented on components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/InputServerStrategy.java
> +            if (data.getMarkerStart().equalsIgnoreCase("Arrow"))
`Arrow` should be declared as a static field, in case it changes and it is used in 4 different locations

2016-10-19 07:23 UTC, mtbc commented on components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/model/FigureTableModel.java
> +                        if (value != null) {
don't need this null check

2016-10-19 07:23 UTC, mtbc commented on components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/model/FigureTableModel.java
> +	}
don't need this space :smiley:

2016-10-19 07:45 UTC, dominikl commented on components/blitz/src/omero/gateway/model/ShapeSettingsData.java
> +        Shape shape = (Shape) asIObject();
I don't think that's necessary, `rtypes.rstring(start)` will return empty string in case of `start == null`.

2016-10-19 07:48 UTC, jburel commented on components/blitz/src/omero/gateway/model/ShapeSettingsData.java
> +        Shape shape = (Shape) asIObject();
I had memory of an exception be thrown, that's why.

2016-10-19 09:23 UTC, dominikl commented on components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/InputServerStrategy.java
> +            if (data.getMarkerStart().equalsIgnoreCase("Arrow"))
Created an Enum for that instead, makes it easier to add more line decorations if needed.

2016-10-19 10:56 UTC, will-moore commented
The "Arrow" toolbar button works as expected.
I updated arrow head size in webclient to match Insight.
I noticed a couple of minor issues in Insight. NB: we don't support Arrow heads on PloyLines in web.
 - If I create a PolyLine I can't add Arrow heads to it. Was that intended (to match web)?
 - However, I can take a Line with Arrows and "break" it into a PolyLine. But when I save this the Arrow heads are lost:


![screen shot 2016-10-19 at 11 49 07](https://cloud.githubusercontent.com/assets/900055/19516185/bf4862a2-95f2-11e6-9ed9-d3d5b940852f.png)

![screen shot 2016-10-19 at 11 49 18](https://cloud.githubusercontent.com/assets/900055/19516189/c555101e-95f2-11e6-90f1-8a332bc9e613.png)

Another minor issue (unrelated to this PR): If I hit the Delete button to delete a shape (only single shape in ROI) the ROI and Shape get removed from the Manager table. But when I hit Save, they show up again (not deleted). However, if I use right-click -> Delete then they are deleted correctly.

2016-10-20 09:06 UTC, dominikl commented
The polyline thing in Insight doesn't work properly anyway. If you save a line ROI and then "break" it and try to save it, you'll get an `org.hibernate.exception.ConstraintViolationException` `constraint [shape_roi_roi_index_key]` exception. Shall we just disable the possibility to "break" line ROIs into polylines? /cc @jburel

2016-10-20 09:48 UTC, will-moore commented
I think we should add a PolyLine button to the toolbar and disable the breaking of lines into PolyLines. 
Most users probably think that you can't draw PolyLines in Insight - it's not very intuitive to draw a line and then break it. Also makes it hard to trace an edge with a PolyLine.
We probably want to keep the ability to break PolyLines and Polygons into smaller segments.

2016-10-20 10:06 UTC, jburel commented
I agree with @will-moore: remove the breaking of lines into polylines (very few people know you can do that!)

2016-10-21 14:33 UTC, jburel commented on components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureArrowFigure.java
> + * org.openmicroscopy.shoola.util.roi.figures.MeasureLineFigure
we have opted to remove that line i.e. line 2 (+this is not correct name)

2016-10-21 14:45 UTC, jburel commented on components/blitz/src/omero/gateway/model/ShapeSettingsData.java
> +        Shape shape = (Shape) asIObject();
you are correct it will return and empty string

2016-10-31 10:40 UTC, dominikl commented
To test commit 2d5c856 : Double click somewhere on a line. The line simply should get selected (like single click), nothing else (before: the line was split into two connected lines (Polyline) at the point of the double click).

2016-10-31 13:41 UTC, jburel commented on components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/InputServerStrategy.java
> +            if (data.getMarkerStart().equalsIgnoreCase("Arrow"))
great

2016-10-31 13:41 UTC, jburel approved these changes

2016-10-31 13:43 UTC, jburel commented on components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureLineFigure.java
> +		if (isReadOnly() || !interactable || !allowSplitSegment)
maybe having a private method ``canBemodified`` will be more suitable
if case we add another constaint

2016-11-02 10:03 UTC, will-moore commented
The line can't be broken now, which is great. But we really need a new PolyLine button on the toolbar so that users can still create PolyLines that way.
I guess that could be done in a separate PR if it's a fair bit of work - but then strictly speaking it should probably be in the same PR as the disabling of line breaking.

2016-11-02 11:50 UTC, dominikl commented
I suppose adding a specific polyline drawing tool will be quite some work. Shall I enable the "line split" functionality again, and create a separate PR for the polyline issue, so that this PR can merged?

2016-11-03 10:13 UTC, jburel commented
Preferable to be done in another PR. @dominikl could you create a card?

2016-11-03 11:29 UTC, dominikl commented
I'll enable the split functionality for Line ROIs again. Created a [trello card](https://trello.com/c/l3IiAu9u/136-roi-tool-bugs-improvements) for the outstanding ROI tool issues.

2016-11-07 12:24 UTC, jburel commented
The "breaking line" is back, this will be removed when/if further work is done on MT

2016-11-07 12:24 UTC, merged