have disk usage plugin cope with multiple IDs given for same class
openmicroscopy/openmicroscopy pull request #4917
Opened 2016-11-01 12:26 UTC by mtbc

# What this PR does

@joshmoore [found that](https://openmicroscopy.slack.com/archives/general/p1478000835010648) `bin/omero fs usage` ignores all but the last of arguments of the form Class:X Class:Y Class:Z so that for identical classes "Class" only the Z is targeted.

# Testing this PR

Check that the `usage` feature of the `fs` CLI plugin now gives sensible results when the same class is mentioned multiple times on the command line.

2016-11-01 12:27 UTC, mtbc commented
@pwalczysko: This bug may indicate a gap in `integration/clitest/`.

2016-11-02 09:51 UTC, simleo requested changes
Suggestion for shortening a common Python idiom

2016-11-02 09:51 UTC, simleo commented on components/tools/OmeroPy/src/omero/plugins/fs.py
>              except:
The above four lines can be shortened to `objects.setdefault(klass, []).extend(ids)`

2016-11-02 16:32 UTC, mtbc commented
For testing there may be useful memories recorded in #3507.

2016-11-02 17:54 UTC, pwalczysko commented
Manual test passes. The order of the Classes is not important, repetition in sense ``Image:1 Image:2...`` is taken into account correctly, so is interspersing like ``Project:1 Dataset:20 Project:2``.

2016-11-02 17:54 UTC, pwalczysko commented
I will need a bit of time for the integration test, unless this is an urgent priority.

2016-11-03 07:53 UTC, mtbc commented
No, things like OMERO 5.3.0-m5 and idr-demo3 are more urgent; if you like I could add a testing card  for this to the QA board.

2016-11-03 09:27 UTC, pwalczysko commented
@mtbc : Yes, please, add a card (and me to it). Thank you

2016-11-03 12:53 UTC, mtbc commented
@simleo: any suggestions for the nested "if" at https://github.com/mtbc/openmicroscopy/blob/94d75e74/components/tools/OmeroPy/src/omero/cli.py#L1862 ?

2016-11-03 17:26 UTC, simleo commented
@mtbc I'd replace lines 1857 to 1871 with:

```python
    shmap = {}
    for req in skipheads:
        combined = shmap.setdefault(req.startFrom[0], req)
        if combined is req:
            continue
        type, ids = req.targetObjects.items()[0]
        combined.targetObjects.setdefault(type, []).extend(ids)
    rv.extend(shmap.itervalues())
```

I've only tested that with mock objects though.

2016-11-04 09:49 UTC, mtbc commented
Thank you. Both good questions. I haven't been able to figure out what this code is doing or why I'm afraid!

2016-11-11 10:32 UTC, mtbc commented
I'm wussing out of fiddling with that bit, it can be for later work.

2016-11-11 10:36 UTC, joshmoore commented
LGTM

2016-11-11 10:50 UTC, mtbc commented
Accidentally closed the PR and now I get to wrestle with Travis again.

2016-11-14 07:52 UTC, joshmoore commented
Quickly merging lest anything happen again.

2016-11-14 07:52 UTC, merged