web api app
openmicroscopy/openmicroscopy pull request #4920
Opened 2016-11-02 13:55 UTC by will-moore

# What this PR does

Moves the new ```/api/``` urls and functionality to a new ```api``` app.

2016-11-04 03:32 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-DEV-merge-push#496](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/496/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/496/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webgateway/views.py

2016-11-04 13:14 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-DEV-merge-push#497](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/497/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/497/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webgateway/views.py

2016-11-07 21:52 UTC, chris-allan requested changes

2016-11-07 21:52 UTC, chris-allan commented on components/tools/OmeroWeb/omeroweb/api/__init__.py
> +
Needs standard file header.

2016-11-07 21:52 UTC, chris-allan commented on components/tools/OmeroWeb/omeroweb/webclient/views.py
> +from omeroweb.api.views import LoginView
The base class should be left in the webgateway. Having interdependence between the `api` and `webclient` application seems like a bad idea. Especially if we decide to move the `api` application into its own repository.

2016-11-07 21:55 UTC, chris-allan commented
As a matter of discussion, in addition to the above review, I don't personally like the camel case decorator class names but I'm not vehemently opposed to them.

/cc @aleksandra-tarkowska, @knabar, @waxenegger

2016-11-10 09:53 UTC, chris-allan approved these changes

2016-11-10 09:54 UTC, chris-allan commented
Ready to merge.

2016-11-10 10:21 UTC, jburel commented
Thanks @chris-allan

2016-11-10 10:21 UTC, merged