Enable script menu only if script available
openmicroscopy/openmicroscopy pull request #4973
Opened 2016-11-30 11:47 UTC by dominikl

# What this PR does

Disables script menus ("Publishing Options") when the respective script is not available.

![screen shot 2016-11-30 at 11 40 27](https://cloud.githubusercontent.com/assets/6575139/20751248/b1abfd0e-b6f2-11e6-9169-d13ef236c6a6.png)

# Testing this PR

Iteratively delete the scripts `Make_Movie.py`, `Thumbnail_Figure.py` and `Split_View_Figure.py` from the server and after each deletion make sure that the respective "Publishing" menu option is disabled. 

# Related reading

[Trello - Figure scripts in Web](https://trello.com/c/237BjWLJ/228-figure-scripts-in-web)

/cc @will-moore

2016-11-30 13:47 UTC, jburel commented
flake8 issues
``

./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:245:52: W291 trailing whitespace
./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:249:1: W293 blank line contains whitespace
./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:251:1: W293 blank line contains whitespace
./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:260:1: W293 blank line contains whitespace
./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:264:1: W293 blank line contains whitespace
./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:271:1: W293 blank line contains whitespace
./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:273:1: W293 blank line contains whitespace
./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:286:80: E501 line too long (109 > 79 characters)
./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:291:80: E501 line too long (89 > 79 characters)
./components/tools/OmeroWeb/omeroweb/webclient/controller/container.py:304:80: E501 line too long (83 > 79 characters)


``

2016-11-30 15:49 UTC, joshmoore requested changes

2016-11-30 15:49 UTC, joshmoore commented on components/tools/OmeroWeb/omeroweb/webclient/controller/container.py
> +            pdb.set_trace()
pdb usage will need removing.

2016-11-30 15:59 UTC, dominikl commented on components/tools/OmeroWeb/omeroweb/webclient/controller/container.py
> +            pdb.set_trace()
Ops, forgot about that. Thanks.

2016-11-30 20:42 UTC, joshmoore submitted a review, later dismissed

2016-12-01 09:58 UTC, pwalczysko commented
Somebody already deleted/disabled the scripts on eel merge ?
![screen shot 2016-12-01 at 09 58 12](https://cloud.githubusercontent.com/assets/2478303/20789538/b59af61c-b7ac-11e6-89e4-22f2807f9c86.png)

2016-12-01 10:03 UTC, will-moore commented
Currently all scripts are available on eel merge:

```
$ omero script list
Previous session expired for root on eel.openmicroscopy.org:4064
Server: [eel.openmicroscopy.org:4064]
Username: [root]
Password:
Created session 271516f3-e2e2-4c79-af15-75ce5a0b6dc0 (root@eel.openmicroscopy.org:4064). Idle timeout: 10 min. Current group: system
 id    | Official scripts                              
-------+-----------------------------------------------
 47301 | /omero/analysis_scripts/Kymograph_Analysis.py 
 48051 | /omero/analysis_scripts/Kymograph.py          
 48052 | /omero/analysis_scripts/Plot_Profile.py       
 46501 | /omero/import_scripts/Populate_Metadata.py    
 7     | /omero/import_scripts/Populate_ROI.py         
 47903 | /omero/figure_scripts/Movie_Figure.py         
 48053 | /omero/figure_scripts/ROI_Split_Figure.py     
 47855 | /omero/figure_scripts/Thumbnail_Figure.py     
 48054 | /omero/figure_scripts/Movie_ROI_Figure.py     
 47906 | /omero/figure_scripts/Split_View_Figure.py    
 47858 | /omero/util_scripts/Dataset_To_Plate.py       
 47859 | /omero/util_scripts/Channel_Offsets.py        
 47860 | /omero/util_scripts/Combine_Images.py         
 48055 | /omero/util_scripts/Images_From_ROIs.py       
 47862 | /omero/export_scripts/Batch_Image_Export.py   
 47863 | /omero/export_scripts/Make_Movie.py           
(16 rows)
```

2016-12-01 10:09 UTC, pwalczysko commented
@will-moore : Yes, I concluded the same. 
I have a workflow which I think is exposing a fatal bug in this PR unfortunately.
  - have web-dev-merge webclient (this PR included)
  - connect it to eel latest server
  - observe that all the menu items are greyed out
  - have web-dev-develop webclient (this PR not included)
  - connect it to the same server, eel latest
  - observe that all the scripts are enabled
  - to make sure the scripts are really available, execute one successfully
  - observe that it works


Conclusion: This PR is greying out the menu items of the publication scripts whether the scripts are available or not.

2016-12-01 10:10 UTC, dominikl commented
Any ideas why it doesn't work on eel? Works fine for me locally.

2016-12-01 11:04 UTC, dominikl commented
There's clearly some mix up here. On http://web-dev-merge.openmicroscopy.org/webclient/ there the figure scripts are missing (only `Make ROI figure` is available there), so disabling the publishing options is correct.. Does web-dev-merge really connect to eel?

![screen shot 2016-12-01 at 11 01 07](https://cloud.githubusercontent.com/assets/6575139/20791598/b6052b8c-b7b5-11e6-949f-f021fdf46ae9.png)

2016-12-01 11:15 UTC, pwalczysko commented
@dominikl : According to your screenshot, you are clicking on wrong menu.
https://github.com/openmicroscopy/openmicroscopy/pull/4973#issuecomment-264143322. It is the publication scripts menu in RHP I was testing.

2016-12-01 11:18 UTC, pwalczysko commented
@dominikl : In the menu you are hightlighting in your comment (the main scripts menu) just click on the "Back" please. Then you will see all the scripts as expected.

2016-12-01 11:19 UTC, dominikl commented
Yes, but the scripts also should be shown in the scripts menu if they are there. If they are missing, the publishing option are disabled, too (that's what the PR does).
There is no `Split View Figure`, `Thumbnail Figure` or `Make Movie` script.

2016-12-01 11:20 UTC, pwalczysko commented
The disabling of the publication scripts cannot be correct. My workflow https://github.com/openmicroscopy/openmicroscopy/pull/4973#issuecomment-264132134 shows that the scripts are present, it is the webclient which is hiding them.

2016-12-01 11:21 UTC, dominikl commented
Ah, the webclient is hiding them... Ok, that's the cause. So I also have to take "hidden" scripts into account. Thanks.

2016-12-02 11:09 UTC, will-moore commented
@dominikl I think after that last commit, you're not using the ```request``` anywhere anymore, so you can remove it from manager.listFigureScripts(request, objs) etc.

2016-12-02 11:11 UTC, will-moore commented on components/tools/OmeroWeb/omeroweb/webclient/controller/container.py
>                              self.image.getSizeZ() > 0)):
@dominikl Not related to this PR, but I think we should only enable Movie if it's a multiple image: The ```sizeT > 1 or sizeZ > 1```.

2016-12-02 11:17 UTC, will-moore commented
Code looks good and it's working fine. Just a couple of minor fixes above.

2016-12-05 10:32 UTC, will-moore commented
Great, thanks.
Good to merge.

2016-12-05 16:05 UTC, merged