Api save whitelist
openmicroscopy/openmicroscopy pull request #5059
Opened 2017-01-26 09:56 UTC by will-moore

# What this PR does

Retricts Save (PUT or POST) to a "whitelist" of supported object types.

# Testing this PR

# Related reading

2017-01-26 10:19 UTC, chris-allan requested changes
We should add some test cases to ensure that the `PUT` and `POST` restrictions are accurate.

2017-01-26 10:19 UTC, chris-allan commented on components/tools/OmeroWeb/omeroweb/api/views.py
> +    can_put = ['Project', 'Dataset', 'Screen']
As these are constants, let's uppercase them.

2017-01-30 03:34 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-DEV-merge-push#577](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/577/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/577/consoleText) for more details.
Possible conflicts:
  - PR #5047 will-moore 'Api wells'
    - components/tools/OmeroWeb/test/integration/test_api_images.py
  - PR #5058 will-moore 'Api child count'
    - components/tools/OmeroWeb/test/integration/test_api_images.py

2017-02-01 03:33 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-DEV-merge-push#579](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/579/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/579/consoleText) for more details.
Possible conflicts:
  - PR #5047 will-moore 'Api wells'
    - components/tools/OmeroWeb/test/integration/test_api_images.py
  - PR #5058 will-moore 'Api child count'
    - components/tools/OmeroWeb/test/integration/test_api_images.py

2017-02-02 03:33 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-DEV-merge-push#580](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/580/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/580/consoleText) for more details.
Possible conflicts:
  - PR #5047 will-moore 'Api wells'
    - components/tools/OmeroWeb/test/integration/test_api_images.py
  - PR #5058 will-moore 'Api child count'
    - components/tools/OmeroWeb/test/integration/test_api_images.py

2017-02-03 03:34 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-DEV-merge-push#581](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/581/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/581/consoleText) for more details.
Possible conflicts:
  - PR #5047 will-moore 'Api wells'
    - components/tools/OmeroWeb/test/integration/test_api_images.py
  - PR #5058 will-moore 'Api child count'
    - components/tools/OmeroWeb/test/integration/test_api_images.py

2017-02-15 13:46 UTC, jburel commented on components/tools/OmeroWeb/omeroweb/api/decorators.py
> +from api_exceptions import NotFoundError, BadRequestError, CreatedObject, \
one per line and alphabetical order

2017-02-15 13:46 UTC, jburel commented on components/tools/OmeroWeb/omeroweb/api/decorators.py
>          # TODO: handle omero.ConcurrencyException
Will you do that in another PR? i.e. TODO

2017-02-15 13:46 UTC, jburel commented on components/tools/OmeroWeb/omeroweb/api/views.py
> +    CreatedObject, MethodNotSupportedError
same

2017-02-15 13:46 UTC, jburel commented on components/tools/OmeroWeb/test/integration/test_api_containers.py
> +        """Test create, update & delete are rejected for unsupported types."""
I think you should split the test and not have ``post/put/delete`` tests in the same one

2017-02-15 23:58 UTC, will-moore commented
Need to fix failing ```test_api_errors.py```` tests in https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-breaking-integration-Python27/164/testReport/
Haven't had time today, so will close this until I fix tests (tomorrow).

2017-02-16 16:48 UTC, will-moore commented on components/tools/OmeroWeb/omeroweb/api/decorators.py
>          # TODO: handle omero.ConcurrencyException
Yes. Hard to see that we need to support ConcurrencyException since we are doing very simple get/set queries now and no stateful services.

2017-02-16 22:44 UTC, will-moore commented on components/tools/OmeroWeb/test/integration/test_api_containers.py
> +        """Test create, update & delete are rejected for unsupported types."""
@jburel I split the test in 102c6c9

2017-02-17 00:10 UTC, will-moore commented
@jburel After those last commits, this is going to conflict with #5058, so we'll need to get that merged ASAP. I still have 3 further api PRs waiting after this one.
@chris-allan You still have "requested changes" on this PR, which I think are addressed with the added tests?

2017-02-17 03:32 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-DEV-merge-push#592](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/592/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/592/consoleText) for more details.
Possible conflicts:
  - PR #5058 will-moore 'Api child count'
    - components/tools/OmeroWeb/test/integration/test_api_errors.py

2017-02-17 09:45 UTC, chris-allan requested changes
Looks great aside from the exception feedback above.

2017-02-17 09:45 UTC, chris-allan commented on components/tools/OmeroWeb/omeroweb/api/api_exceptions.py
> +    def __init__(self, message, stacktrace=None):
I'm not seeing any use of the `stacktrace` keyword argument in the implementation. Is it your intention to use it for something? If so, what? If you want to have a unified constructor prototype that is similar to the other exceptions you have above then I would suggest making a class hierarchy so you are not having to implement, and document, this every time.

2017-02-17 11:11 UTC, will-moore commented
@chris-allan Thanks. Fixed in https://github.com/openmicroscopy/openmicroscopy/pull/5059/commits/eb18edcb38a5c89c68b7fa0d1f5221ed4af836d7

2017-02-17 17:20 UTC, chris-allan approved these changes

2017-02-17 19:08 UTC, jburel commented
Exception code fixed.
Tests split and passing
I will merge on Monday am everything is green

2017-02-20 10:45 UTC, merged