privileges canChgrp
openmicroscopy/openmicroscopy pull request #5352
Opened 2017-06-29 14:28 UTC by will-moore

# What this PR does

Fixes bug of Light Admin without ```canChgrp``` privilege still being able to do chgrp in webcilent.
See "crash on Move in not-your-group" checkbox in https://trello.com/c/LUzfIhaU/46-crashes-in-webclient 

# Testing this PR

1.  Create a Light Admin user without ```Chgrp``` privilege
1. User shouldn't be able to chgrp other users' data (right-click menu item "Move to Group" should be disabled.
1. Full Admin or Light Admin with ```Chgrp``` privilege should still be able to move others' data.
1. Users or Light Admins without ```Chgrp``` should still be able to move their own data.

cc @pwalczysko @mtbc

2017-06-29 14:32 UTC, mtbc commented
It's probably outwith this PR but FYI when one has the actual object's details in hand we now have a couple more can* methods that should always work: `canChgrp()` and `canChown()` at http://www.openmicroscopy.org/site/support/omero5.3-staging/developers/Server/Permissions.html#permissions-object.

2017-06-29 14:53 UTC, will-moore commented
@mtbc - It would be nice to user server logic for ```canChgrp``` but I don't see that flag on that permissions object.
This permissions object is returned from the "magic" mapping of ```project_details_permissions``` in this query:
```
        select new map(project.id as id,
               project.name as name,
               project.details.owner.id as ownerId,
               project as project_details_permissions,
               (select count(id) from ProjectDatasetLink pdl
                where pdl.parent = project.id) as childCount)
        from Project project
```
When I print it, it's just a dict:
```
{'canDelete': True, 'canAnnotate': True, 'canEdit': True, 'perm': 'rwr---', 'canLink': True}
```

2017-06-29 15:08 UTC, mtbc commented
Huh, that's interesting. Your `omero_model_Permissions_ice.py` has `canChgrp`? I wonder if there's some Pythonic thing somewhere on the way to the web client that I didn't know about. `canChgrp()` is working fine from the Java integration tests.

2017-06-29 16:34 UTC, pwalczysko commented
travis failing.

2017-06-30 08:43 UTC, will-moore commented
Ah, I didn't realise that @mtbc's PR wasn't getting included in the merged build yet.
So, currently this PR is causing a crash when you try to load another user's data in the tree.
I need to exclude this or open against roles. Currently impossible to test my other PRs.

2017-06-30 08:44 UTC, mtbc commented
My PR's in breaking: feel free to add `--breaking` and use https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-trigger/.

2017-06-30 08:44 UTC, will-moore commented
--breaking

2017-07-03 11:55 UTC, pwalczysko commented
All four tests from the header of this PR passed. All works as expected.
Although the ``canChgrp`` missing question is still to be solved, I suggest we merge this PR as it fixes the crashes in appropriate manner.

2017-07-04 09:02 UTC, jburel commented
not included in today's build
Removing breaking label so it goes along @mtbc "migration" PR

2017-07-04 11:24 UTC, mtbc commented
With #5358 that kind of query now gives me results like `{'canDelete': True, 'canAnnotate': False, 'perm': 'rw----', 'canChown': False, 'canChgrp': False, 'canLink': False, 'canEdit': True}`.

2017-07-14 10:49 UTC, sbesson requested changes
One stylistic request, then this is good to merge.

2017-07-14 10:49 UTC, sbesson commented on components/tools/OmeroWeb/omeroweb/webclient/tree.py
> +            "Chgrp" in conn.getEventContext().adminPrivileges):
Looks good. For unification of our codebase, can this be adjusted to use the enums as in https://github.com/openmicroscopy/openmicroscopy/pull/5376/files#diff-4c592a4ec58d6f4830c88b81f8aa77a3R66

2017-07-31 23:02 UTC, will-moore commented
Use canChgrp from #5358 now.
Needs retest.

2017-08-02 17:19 UTC, pwalczysko commented
The UI  retest indicated in https://github.com/openmicroscopy/openmicroscopy/pull/5352#issuecomment-319220794 and started according to the header of this PR fails on:

  - full admin has no "Move" menu item enabled on any objects of another user (user-4, who is a member of at least 2 groups)
  - the same for light admin  with ``Chgrp`` privilege

2017-08-03 08:29 UTC, will-moore commented
For some reason, the functionality added in #5358 has stopped working and the ```project_details_permissions``` map queries return a permissions dict that is missing the ```canChgrp``` and ```canChown``` flags.
This is why @pwalczysko's retest failed, but we also see Robot test failures etc.

2017-08-10 14:08 UTC, mtbc commented
I haven't yet managed to reproduce the *missing* flags locally (via `bin/omero hql`) but I'll keep investigating.

2017-08-11 12:47 UTC, mtbc commented
So, while I *am* always getting those map entries, they are wrongly `false` even for `root` so they may not be of much help anyway. This probably fell through the cracks because I had no idea that the `_details_permissions` hack even existed. I created https://trello.com/c/QbdB9M8k/115-canchgrp-canchown-bug and am not yet easily seeing a fix.

2017-08-11 14:54 UTC, will-moore commented
@mtbc Before this PR, there was no check that the permissions loaded like this:
```
perms2 = unwrap(reader.projection((
                "select new map(p.id as id, p as p_details_permissions) "
                "from Project p where p.id = :id"),
                ParametersI().addId(project.id.val)))[0][0]
```
were correct, partly because the ```ProjectionFixtures``` at https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroPy/src/omero/testlib/__init__.py#L1132 didn't have the ```canChgrp``` and ```canChown``` added to them, and because the ```def assertPerms(perms, fixture)``` used in the test didn't check for ```canChgrp``` and ```canChown```. Adding these checks on the 1st August caused the tests to start failing.

2017-08-14 09:08 UTC, will-moore commented
@mtbc I'll close this until we have canChgrp flag working in ```_details_permissions``` dict, so we don't have so many tests failing... cc @joshmoore

2017-08-15 05:30 UTC, joshmoore commented
Ooops. Forgot to point out that this can likely be re-opened with https://github.com/openmicroscopy/openmicroscopy/pull/5437 though at this point we can await the status of this mornings integration tests: https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration/748/

2017-08-15 11:55 UTC, will-moore commented
Reopening this to test against #5437.

2017-08-16 05:34 UTC, will-moore commented
Test permissions now passing with #5437 https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-Python27/630/testReport/OmeroPy.test.integration.test_permissions/

2017-08-16 09:21 UTC, joshmoore commented on components/tools/OmeroWeb/test/unit/test_tree.py
> +            # expected.append('canChgrp')
Can this be removed?

2017-08-16 09:29 UTC, joshmoore commented
@sbesson : I assume you're happy with this?

2017-08-16 09:38 UTC, sbesson approved these changes

2017-08-21 07:43 UTC, mtbc approved these changes
Great to see all the tests.

2017-08-21 09:12 UTC, merged