Fixed rgb_int2css and rgb_int2rgba
openmicroscopy/openmicroscopy pull request #5451
Opened 2017-08-18 13:28 UTC by dominikl

Both methods calculated alpha as fraction of 256 whereas
it should have been 255 ( alpha int value [0, 255] )

(was introduced by #4995 , thanks for spotting this issue!)

/cc @jburel @chris-allan

2017-08-21 08:56 UTC, chris-allan requested changes

2017-08-21 08:56 UTC, chris-allan commented on components/tools/OmeroWeb/test/unit/test_marshal.py
> +    shape.strokeColor = rlong(287454207)     # 0x112233FF,r=17,g=34,b=51,a=255
This value is a 32-bit integer (`rint`) not an `rlong`.

2017-08-21 08:56 UTC, chris-allan commented on components/tools/OmeroWeb/test/unit/test_marshal.py
> +    shape.strokeColor = rlong(287453952)     # 0x11223300,r=17,g=34,b=51,a=0
This value is a 32-bit integer (`rint`) not an `rlong`.

2017-08-21 08:56 UTC, chris-allan commented on components/tools/OmeroWeb/test/unit/test_marshal.py
> +    def test_rgba(self, basic_ellipse, basic_line, basic_polyline):
Probably a good idea to include some values < 0. This has really tripped us up in the past. These are instances where the red component is > 127 (`0x7f`). Can be easily achieved by using the `ctypes` module:

```
In [1]: import ctypes

In [2]: ctypes.c_int(0x800000ff).value
Out[2]: -2147483393
```

/cc @will-moore

2017-08-21 15:09 UTC, chris-allan approved these changes

2017-08-22 07:38 UTC, mtbc commented
Need to run flake8 on `test_marshal.py`.

2017-08-23 14:05 UTC, jburel commented on components/tools/OmeroWeb/test/unit/test_marshal.py
> +    shape.strokeColor = rint(ctypes.c_int(0x112233FF).value)
still useful to have
so maybe
```
# r=17,g=34,b=51,a=255
shape.strokeColor = rint(ctypes.c_int(0x112233FF).value)
```

2017-08-25 10:39 UTC, jburel commented
Thanks @dominikl

2017-08-25 10:39 UTC, merged