Web diagnostics
openmicroscopy/openmicroscopy pull request #5474
Opened 2017-08-28 12:17 UTC by dominikl

# What this PR does

`./omero admin diagnostics` also checks status and logs of OMERO.web, but as OMERO.web could be run independantly, it falsely reports an error in that case.
This PR removes the 'web' part from 'admin diagnostics' and puts it into the web module as 'web diagnostics'

# Testing this PR

- Run `./omero admin diagnostics` and check that you don't see any web related output.
- Run `./omero web diagnostics` and check that you see all the web related output.

# Related reading

https://trello.com/c/XdIDdBNS/137-omero-admin-diagnostics-web-status-is-misleading

2017-08-29 08:39 UTC, dominikl commented
I did quite a lot copy/pasting (methods like `sz_str`, `item`) from admin.py to web.py. Guess there's a better way to do this, worth it?

2017-08-29 10:22 UTC, sbesson reviewed
Agreed re  code duplication. Thinking of the ongoing micro-services, I could imagine some of this logic re-use more generically e.g. for an `bin/omero thumbnails-ms diagnostics`.

An immediate way to refactor would be to derive a new subclass of `BaseControl` with the helper methods in `cli.py` and make `AdminControl` and `WebControl`  inherit it.

2017-08-29 10:22 UTC, sbesson commented on components/tools/OmeroPy/src/omero/plugins/web.py
> +        from omero.plugins.web import WebControl
Since this is now a method in `Webcontrol`, this import is unecessary and `status(args)` can be used directly 2 lines below

2017-08-29 10:26 UTC, joshmoore commented
Something for a follow-on:

> An immediate way to refactor would be to derive a new subclass of BaseControl with the helper methods in cli.py and make AdminControl and WebControl inherit it.

`ctx` provides access to all `Control` objects. Perhaps instead we make an interface `DiagnosticsControl` and use multiple inheritance. Then `bin/omero diagnostics` could loop through all such controls.

2017-08-29 15:48 UTC, dominikl commented
Moved the common methods to `BaseControl`. Is that better? By the way, I'm getting way out of my python comfort zone here... ;-)

2017-08-31 08:14 UTC, joshmoore commented
Pushed 11413f02d380b94c590b02a3a7b441a6dbfc115f for discussion. To some extent, this _reintroduces_ the confusion of `bin/omero admin diagnostics`, so we'd need to decide if this "advanced usage" is worth it. Regardless, it does introduce a more formal "diagnostics API" which may be worthwhile.

cc: @jburel @sbesson

2017-09-06 09:38 UTC, joshmoore commented
Opened https://github.com/dominikl/openmicroscopy/pull/9 *without* the `bin/omero diagnostics` command (which I'll add to github.com/joshmoore/omero-cli-diagnostics)

2017-09-18 20:51 UTC, jburel commented
@dominikl can we retest this PR?

2017-09-19 07:03 UTC, dominikl commented
Yes, I think so. Sorry should have listed it on standup.

2017-09-20 11:22 UTC, manics requested changes
Looks fine apart from the help text.

2017-09-20 11:22 UTC, manics commented on components/tools/OmeroPy/src/omero/cli.py
> +            "preferably active ")
preferably active... `server`? `application`?
```
$ omero admin --help
...
  <subcommand>
    diagnostics       Run a set of checks on the current, preferably active
    start             Start icegridnode daemon and waits for required components to come up, i.e. status == 0
...
```

2017-09-22 08:45 UTC, manics commented
Good to merge

2017-09-22 08:47 UTC, merged