Ignore PlaneInfo annotations
openmicroscopy/openmicroscopy pull request #5522
Opened 2017-09-28 10:39 UTC by dominikl

# What this PR does

If an ome.tiff contains annotations of PlaneInfo objects the import crashes with a RuntimeException. With this PR no exception will be thrown, just a warning logged (like it's already done if the annotation target is null).

# Testing this PR

Import the file from https://www.openmicroscopy.org/qa2/qa/feedback/17938/ 

# Related reading

https://trello.com/c/1sX3tep3/62-bug-creating-annotations-on-plane

2017-10-11 07:20 UTC, mtbc commented on components/blitz/src/ome/formats/model/ReferenceProcessor.java
> +                log.warn("Ignoring target class " + target+", not handled yet.");
spaces around `+`

2017-10-11 09:49 UTC, rleigh-codelibre commented
Looks fine to me, and importing the image shows success with the warnings in the import log.

2017-10-11 13:22 UTC, dominikl commented
Thanks @rleigh-codelibre . Just also fixed the formatting issue noticed by @mtbc (no re-testing needed imho).

2017-10-23 12:17 UTC, chris-allan requested changes
The reason why this exception was originally thrown was to catch logic errors in Bio-Formats readers. Especially cases where mappings were missing or needed to be written. Fundamentally, I would not remove it.

Has the root cause of the original error been located?

2017-10-23 13:40 UTC, dominikl commented
Ok, then I close this PR again. So basically the file is invalid? Not sure if that's been made very clear in @rleigh-codelibre 's forum reply: https://www.openmicroscopy.org/community/viewtopic.php?f=6&t=8371

2017-10-23 13:40 UTC, closed without merging

2017-10-23 13:57 UTC, rleigh-codelibre commented
From the point of view of annotations and annotation references, the file is valid and can be processed to add these annotations and references to the metadata store.  OMERO isn't handling these valid references.  There are some classes which are annotatable in the data model which aren't annotatable with OMERO.

The example in the forum had some odd (but valid) *content* inside the annotation, but the annotations and annotation references themselves were fine.

2017-10-23 14:36 UTC, chris-allan commented
In cases of mismatch between the models we have to do the work to either perform the correct mapping or ignore cases where we have references to objects that are not annotatable in OMERO. That's a fine solution to this issue that doesn't result in removing a safety check from the reference handling.