add entry for 5.6.6
openmicroscopy/openmicroscopy pull request #6337
Opened 2022-12-08 10:27 UTC by jburel

# What this PR does

Add entry for the upcoming 5.6.6 release

2022-12-08 21:11 UTC, sbesson requested changes
Two suggestions. I have not looked through the complete list of changes across acll components but I assume this focuses on the end-user facing ones

2022-12-08 21:11 UTC, sbesson commented on history.rst
> +- enhancement of the Command line importer developer user experience
Possibly clarify this is the Java command line importer?

2022-12-08 21:11 UTC, sbesson commented on history.rst
> +- a new property to configure the QA system the feedback is submitted to.
Worth naming it?

2022-12-09 09:10 UTC, jburel commented
@sbesson adjustment made

2022-12-09 09:24 UTC, sbesson approved these changes

2022-12-09 09:28 UTC, merged