Add a test case for ome/omero-py#418
openmicroscopy/openmicroscopy pull request #6396
Opened 2024-07-08 12:06 UTC by chris-allan

# What this PR does

Add a test case for ome/omero-py#418

2024-07-09 08:10 UTC, sbesson requested changes
CI execution has been failing overnight due to unrelated infrastructure issues. One syntactic issue to allow the test to be picked up by `pytest`.

Only other wonder if whether we also want to expand the test semantics to ensure that the output

```
table.read(colNumbers, start, stop, context)
table.readCoordinates(rowNumbers, context)
```

also respect the new `omero.tables.include_row_numbers` key/value pair

2024-07-09 08:10 UTC, sbesson commented on components/tools/OmeroPy/test/integration/tablestest/test_service.py
> +    def tesIncludeRowNumbers(self):
```suggestion
    def testIncludeRowNumbers(self):
```
is likely required to be picked up by `pytest`

2024-07-11 05:50 UTC, will-moore commented
Code looks good, apart from typo mentioned above.

2024-07-12 04:25 UTC, jburel commented
test is green, upstream PR has now been. merged

2024-07-12 08:14 UTC, sbesson approved these changes
All three new integration tests were included in the nightly CI builds, executed successfully and should cover all OMERO.tables API that have support for the new boolean

2024-07-12 10:19 UTC, merged